// Mocks generated by Mockito 5.4.5 from annotations
// in sofomo/test/presentation/repository_search/bloc/repository_search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:async/async.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sofomo/domain/model/repositories_page.dart' as _i6;
import 'package:sofomo/domain/repository/repository_repository.dart' as _i2;
import 'package:sofomo/domain/use_case/search_repositories_use_case.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRepositoryRepository_0 extends _i1.SmartFake
    implements _i2.RepositoryRepository {
  _FakeRepositoryRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchRepositoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepositoryUseCase extends _i1.Mock
    implements _i4.SearchRepositoryUseCase {
  @override
  _i2.RepositoryRepository get repositoryRepository => (super.noSuchMethod(
        Invocation.getter(#repositoryRepository),
        returnValue: _FakeRepositoryRepository_0(
          this,
          Invocation.getter(#repositoryRepository),
        ),
        returnValueForMissingStub: _FakeRepositoryRepository_0(
          this,
          Invocation.getter(#repositoryRepository),
        ),
      ) as _i2.RepositoryRepository);

  @override
  _i5.Future<_i3.Result<_i6.RepositoriesPage>> call({
    required String? searchText,
    int? page = 1,
    int? perPage = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #searchText: searchText,
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i5.Future<_i3.Result<_i6.RepositoriesPage>>.value(
            _FakeResult_1<_i6.RepositoriesPage>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #searchText: searchText,
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Result<_i6.RepositoriesPage>>.value(
                _FakeResult_1<_i6.RepositoriesPage>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #searchText: searchText,
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i5.Future<_i3.Result<_i6.RepositoriesPage>>);
}
