// Mocks generated by Mockito 5.4.5 from annotations
// in sofomo/test/presentation/repository_details/bloc/repository_details_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:async/src/result/result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sofomo/domain/model/repository.dart' as _i5;
import 'package:sofomo/domain/use_case/get_repository_use_case.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRepositoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRepositoryUseCase extends _i1.Mock
    implements _i3.GetRepositoryUseCase {
  @override
  _i4.Future<_i2.Result<_i5.Repository>> call(int? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.Repository>>.value(
            _FakeResult_0<_i5.Repository>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Result<_i5.Repository>>.value(
            _FakeResult_0<_i5.Repository>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.Repository>>);
}
